{{redirect|Circadian|the album|Circadian (album)}}
{{for|the 2005 film|Circadian Rhythm (film)}}
{{Infobox body process
|name              = Circadian rhythm
|image             = File:Biological clock human.svg|thumb|
|caption           = Some features of the human circadian (24-hour) biological clock
|organisms         = 
|biological system =  
|health            = 
|action            = 
|stimuli           = 
|method            = 
|outcome           = 
|frequency         = 24 hr
|duration          = 
|footnote          = 
}}
A '''circadian rhythm''' {{IPAc-en|s|ɜː|ˈ|k|eɪ|d|i|ə|n}} is any biological process that displays an [[Endogeny|endogenous]], [[entrainment (chronobiology)|entrainable]] [[oscillation]] of about 24 hours. These 24-hour rhythms are driven by a [[circadian clock]], and they have been widely observed in [[plants]], [[animals]], [[fungi]], and [[cyanobacteria]].<ref name="Edgar 459–464">{{cite journal | vauthors = Edgar RS, Green EW, Zhao Y, van Ooijen G, Olmedo M, Qin X, Xu Y, Pan M, Valekunja UK, Feeney KA, Maywood ES, Hastings MH, Baliga NS, Merrow M, Millar AJ, Johnson CH, Kyriacou CP, O'Neill JS, Reddy AB | title = Peroxiredoxins are conserved markers of circadian rhythms | journal = Nature | volume = 485 | issue = 7399 | pages = 459–64 | date = May 2012 | pmid = 22622569 | pmc = 3398137 | doi = 10.1038/nature11088 | url = http://www.nature.com/nature/journal/v485/n7399/full/nature11088.html | bibcode = 2012Natur.485..459E }}</ref>

The term ''circadian'' comes from the [[Latin]] ''[[circa]]'', meaning "around" (or "approximately"), and ''diēm'', meaning "day". The formal study of biological temporal rhythms, such as daily, [[tidal]], weekly, seasonal, and annual rhythms, is called [[chronobiology]]. Processes with 24-hour oscillations are more generally called '''diurnal rhythms'''; strictly speaking, they should not be called circadian rhythms unless their endogenous nature is confirmed.<ref name="Vitaterna 2001">{{cite journal | vauthors = Vitaterna MH, Takahashi JS, Turek FW | title = Overview of circadian rhythms | journal = Alcohol Research & Health | volume = 25 | issue = 2 | pages = 85–93 | date = 2001 | pmid = 11584554 | url = http://pubs.niaaa.nih.gov/publications/arh25-2/85-93.htm }}</ref>

Although circadian rhythms are endogenous ("built-in", self-sustained), they are adjusted (entrained) to the local environment by external cues called [[zeitgeber]]s (from German, "time giver"), which include light, temperature and [[redox]] cycles. In medical science,  an abnormal circadian rhythm in humans is known as [[circadian rhythm disorder]].<ref name="Bass 348–356">{{cite journal | vauthors = Bass J | title = Circadian topology of metabolism | journal = Nature | volume = 491 | issue = 7424 | pages = 348–56 | date = November 2012 | pmid = 23151577 | doi = 10.1038/nature11704 | url = http://www.nature.com/nature/journal/v491/n7424/full/nature11704.html | bibcode = 2012Natur.491..348B }}</ref>

In 2017, the [[Nobel Prize in Physiology or Medicine]] was awarded to [[Jeffrey C. Hall]], [[Michael Rosbash]] and [[Michael W. Young]] "for their discoveries of molecular mechanisms controlling the circadian rhythm" in [[Drosophila|fruit flies]].<ref name=nobel17>{{Cite web|url=https://www.nobelprize.org/nobel_prizes/medicine/laureates/2017/|title=The Nobel Prize in Physiology or Medicine 2017|website=www.nobelprize.org|access-date=2017-10-06}}</ref>

==History==
The earliest recorded account of a circadian process dates from the 4th century BC, when [[Androsthenes of Thasos|Androsthenes]], a ship captain serving under [[Alexander the Great]], described [[diurnality|diurnal]] leaf movements of the [[tamarind]] tree.<ref>{{Cite book |author=Bretzl H |title=Botanische Forschungen des Alexanderzuges |location=Leipzig |publisher=Teubner |year=1903}}{{Page needed|date=September 2010}}</ref> The observation of a circadian or diurnal process in humans is mentioned in [[History of Chinese medicine|Chinese medical texts]] dated to around the [[13th century]], including the ''Noon and Midnight Manual'' and the ''Mnemonic Rhyme to Aid in the Selection of Acu-points According to the Diurnal Cycle, the Day of the Month and the Season of the Year''.<ref name="cl">{{cite book|author=Gwei-Djen Lu|title=Celestial Lancets|date=25 October 2002|publisher=Psychology Press|isbn=978-0-7007-1458-2|pages=137–140}}</ref>

The first recorded observation of an endogenous [[circadian clock|circadian oscillation]] was by the French scientist [[Jean-Jacques d'Ortous de Mairan]] in 1729. He noted that 24-hour patterns in the movement of the leaves of the plant ''[[Mimosa pudica]]'' continued even when the plants were kept in constant darkness, in the first experiment to attempt to distinguish an endogenous clock from responses to daily stimuli.<ref name="de mairan 1729">{{Cite journal | author=de Mairan JJO | title=Observation Botanique | journal=Histoire de l'Academie Royale des Sciences | year=1729 | pages=35–36}}</ref><ref name="pmid16761955">{{cite journal | vauthors = Gardner MJ, Hubbard KE, Hotta CT, Dodd AN, Webb AA | title = How plants tell the time | journal = The Biochemical Journal | volume = 397 | issue = 1 | pages = 15–24 | date = July 2006 | pmid = 16761955 | pmc = 1479754 | doi = 10.1042/BJ20060484 }}</ref>

In 1896, Patrick and Gilbert observed that during a prolonged period of sleep deprivation, sleepiness increases and decreases with a period of approximately 24 hours.<ref>{{cite journal | vauthors = Dijk DJ, von Schantz M | title = Timing and consolidation of human sleep, wakefulness, and performance by a symphony of oscillators | journal = Journal of Biological Rhythms | volume = 20 | issue = 4 | pages = 279–90 | date = August 2005 | pmid = 16077148 | doi = 10.1177/0748730405278292 }}</ref> In 1918, J.S. Szymanski showed that animals are capable of maintaining 24-hour activity patterns in the absence of external cues such as light and changes in temperature.<ref>{{Cite journal |author=Danchin A |title=Important dates 1900–1919 |journal=HKU-Pasteur Research Centre |location=Paris |url=http://www.pasteur.fr/recherche/unites/REG/causeries/dates_1900.html |archive-url=https://web.archive.org/web/20031020031510/http://www.pasteur.fr/recherche/unites/REG/causeries/dates_1900.html |dead-url=yes |archive-date=2003-10-20 |access-date=2008-01-12 }}</ref> In the early 20th century, circadian rhythms were noticed in the rhythmic feeding times of bees. Extensive experiments were done by [[Auguste Forel]], [[Ingeborg Beling]], and Oskar Wahl to see whether this rhythm was due to an endogenous clock.<ref>{{cite journal | vauthors = Antle MC, Silver R | title = Neural basis of timing and anticipatory behaviors | journal = The European Journal of Neuroscience | volume = 30 | issue = 9 | pages = 1643–9 | date = November 2009 | pmid = 19878281 | pmc = 2929840 | doi = 10.1111/j.1460-9568.2009.06959.x }}</ref> The existence of circadian rhythm was independently discovered in the fruit fly ''Drosophila melanogaster'' in 1935 by two German zoologists, Hans Kalmus and Erwin Bünning.<ref>{{cite journal|last1=Bruce|first1=Victor G.|last2=Pittendrigh|first2=Colin S.|title=Endogenous Rhythms in Insects and Microorganisms|journal=The American Naturalist|date=1957|volume=91|issue=858|pages=179–195|doi=10.1086/281977}}</ref><ref name=pitt93>{{cite journal | vauthors = Pittendrigh CS | title = Temporal organization: reflections of a Darwinian clock-watcher | journal = Annual Review of Physiology | volume = 55 | issue = 1 | pages = 16–54 | date = 1993 | pmid = 8466172 | doi = 10.1146/annurev.ph.55.030193.000313 }}</ref>

In 1954, an important experiment was reported by [[Colin Pittendrigh]] who showed that eclosion (the process of pupa turning into adult)  in ''[[Drosophila pseudoobscura|D. pseudoobscura]]'' was a circadian behaviour. He demonstrated that temperature played a vital role in eclosion rhythm, the period of eclosion was delayed but not stopped when temperature was decreased.<ref>{{cite journal | vauthors = Pittendrigh CS | title = ON TEMPERATURE INDEPENDENCE IN THE CLOCK SYSTEM CONTROLLING EMERGENCE TIME IN DROSOPHILA | journal = Proceedings of the National Academy of Sciences of the United States of America | volume = 40 | issue = 10 | pages = 1018–29 | date = October 1954 | pmid = 16589583 | pmc = 534216 | doi = 10.1073/pnas.40.10.1018 }}</ref> It was an indication that circadian rhythm was controlled by an internal biological clock.<ref name=pitt93/> The term ''circadian'' was coined by [[Franz Halberg]] in 1959.<ref>{{cite journal | vauthors = Halberg F, Cornélissen G, Katinas G, Syutkina EV, Sothern RB, Zaslavskaya R, Halberg F, Watanabe Y, Schwartzkopff O, Otsuka K, Tarquini R, Frederico P, Siggelova J | title = Transdisciplinary unifying implications of circadian findings in the 1950s | journal = Journal of Circadian Rhythms | volume = 1 | issue = 1 | pages = 2 | date = October 2003 | pmid = 14728726 | pmc = 317388 | doi = 10.1186/1740-3391-1-2 | quote = Eventually I reverted, for the same reason, to "circadian" ... | displayauthors = et al. }}</ref> According to Halberg's original definition:
{{Quote|The term "circadian" was derived from ''circa'' (about) and ''dies'' (day); it may serve to imply that certain physiologic periods are close to 24 hours, if not exactly that length. Herein, "circadian" might be applied to all "24-hour" rhythms, whether or not their periods, individually or on the average, are different from 24 hours, longer or shorter, by a few minutes or hours.<ref>{{cite journal|last1=Halberg|first1=F.|title=Physiologic 24-hour periodicity: general and procedural considerations with reference to the adrenal cycle|journal=Zeitschrift für Vitamin- Hormone- und Fermentforschung|date=1959|volume=10|pages=225–296}}</ref><ref name="kouk">{{cite book|last1=Koukkari|first1=Willard L.|last2=Sothern|first2=Robert B.|title=Introducing Biological Rhythms: A Primer on the Temporal Organization of Life, with Implications for Health, Society, Reproduction, and the Natural Environment|date=2006|publisher=Springer|location=New York|isbn=978-1-4020-3691-0|page=23|url=https://books.google.co.in/books?id=jQWVfKcdct8C&pg}}</ref>}}

In 1977, the International Committee on Nomenclature of the International Society for Chronobiology formally adopted the definition, which states:
{{Quote|Circadian: relating to biologic variations or rhythms with a frequency of 1 cycle in 24 ± 4 h; ''circa'' (about, approximately) and ''dies'' (day or 24 h). Note: term describes rhythms with an about 24-h cycle length, whether they are frequency-synchronized with (acceptable) or are desynchronized or free-running from the local environmental time scale, with periods of slightly yet consistently different from 24-h.<ref>{{cite journal | vauthors = Halberg F, Carandente F, Cornelissen G, Katinas GS | title = [Glossary of chronobiology (author's transl)] | journal = Chronobiologia | volume = 4 Suppl 1 | pages = 1–189 | date = 1977 | pmid = 352650 }}</ref>}}

[[Ron Konopka]] and [[Seymour Benzer]] identified the first clock mutant in ''Drosophila'' in 1971 and called it "[[period (gene)|period]]" (''per'') gene, the first discovered genetic determinant of behavioral rhythmicity.<ref name="pmid5002428">{{cite journal | vauthors = Konopka RJ, Benzer S | title = Clock mutants of Drosophila melanogaster | journal = Proceedings of the National Academy of Sciences of the United States of America | volume = 68 | issue = 9 | pages = 2112–6 | date = September 1971 | pmid = 5002428 | pmc = 389363 | doi = 10.1073/pnas.68.9.2112 | bibcode = 1971PNAS...68.2112K }}</ref> ''per'' gene was isolated in 1984 by two teams of researchers. Konopka, Jeffrey Hall, Michael Roshbash and their team showed that ''per'' locus is the centre of the circadian rhythm, and that loss of ''per'' stops circadian activity.<ref name=reddy>{{cite journal | vauthors = Reddy P, Zehring WA, Wheeler DA, Pirrotta V, Hadfield C, Hall JC, Rosbash M | title = Molecular analysis of the period locus in Drosophila melanogaster and identification of a transcript involved in biological rhythms | journal = Cell | volume = 38 | issue = 3 | pages = 701–10 | date = October 1984 | pmid = 6435882 | doi = 10.1016/0092-8674(84)90265-4 }}</ref><ref name=zehring>{{cite journal | vauthors = Zehring WA, Wheeler DA, Reddy P, Konopka RJ, Kyriacou CP, Rosbash M, Hall JC | title = P-element transformation with period locus DNA restores rhythmicity to mutant, arrhythmic Drosophila melanogaster | journal = Cell | volume = 39 | issue = 2 Pt 1 | pages = 369–76 | date = December 1984 | pmid = 6094014 | doi = 10.1016/0092-8674(84)90015-1 }}</ref>  At the same time, Michael W. Young's team reported similar effects of ''per'', and that the gene covers 7.1-kilobase (kb) interval on the X chromosome and encodes a 4.5-kb poly(A)+ RNA.<ref name=bargi1>{{cite journal | vauthors = Bargiello TA, Jackson FR, Young MW | title = Restoration of circadian behavioural rhythms by gene transfer in Drosophila | journal = Nature | volume = 312 | issue = 5996 | pages = 752–4 | date = 1984 | pmid = 6440029 | doi = 10.1038/312752a0 }}</ref><ref name=bargi2>{{cite journal | vauthors = Bargiello TA, Young MW | title = Molecular genetics of a biological clock in Drosophila | journal = Proceedings of the National Academy of Sciences of the United States of America | volume = 81 | issue = 7 | pages = 2142–6 | date = April 1984 | pmid = 16593450 | pmc = 345453 | doi = 10.1038/312752a0 }}</ref> They went on to discover the key genes and neurones in ''Drosophila'' circadian system, for which Hall, Rosbash and Young received the [[Nobel Prize in Physiology or Medicine|Nobel Prize in Physiology or Medicine 2017]].<ref name=nobel17/>

[[Joseph Takahashi]] discovered the first mammalian circadian clock mutation (''clockΔ19'') using mice in 1994.<ref>{{MEDRS|date=November 2013}} {{Cite news |title=Gene Discovered in Mice that Regulates Biological Clock |work=Chicago Tribune |date=29 April 1994}}</ref><ref>{{primary source inline|date=November 2013}} {{cite journal | vauthors = Vitaterna MH, King DP, Chang AM, Kornhauser JM, Lowrey PL, McDonald JD, Dove WF, Pinto LH, Turek FW, Takahashi JS | title = Mutagenesis and mapping of a mouse gene, Clock, essential for circadian behavior | journal = Science | volume = 264 | issue = 5159 | pages = 719–25 | date = April 1994 | pmid = 8171325 | pmc = 3839659 | doi = 10.1126/science.8171325 | displayauthors = etal }}</ref> However, recent studies show that deletion of ''clock'' does not lead to a behavioral phenotype (the animals still have normal circadian rhythms), which questions its importance in rhythm generation.<ref>{{cite journal | vauthors = Debruyne JP, Noton E, Lambert CM, Maywood ES, Weaver DR, Reppert SM | title = A clock shock: mouse CLOCK is not required for circadian oscillator function | journal = Neuron | volume = 50 | issue = 3 | pages = 465–77 | date = May 2006 | pmid = 16675400 | doi = 10.1016/j.neuron.2006.03.041 }}</ref><ref>{{cite journal | vauthors = Collins B, Blau J | title = Keeping time without a clock | journal = Neuron | volume = 50 | issue = 3 | pages = 348–50 | date = May 2006 | pmid = 16675389 | doi = 10.1016/j.neuron.2006.04.022 }}</ref>

==Criteria==

To be called circadian, a biological rhythm must meet these three general criteria:<ref>{{cite book|last=Johnson|first=Carl|title=Chronobiology: Biological Timekeeping|year=2004|publisher=Sinauer Associates, Inc.|location=Sunderland, Massachusetts, USA|pages=67–105}}</ref> 
# '''The rhythm has an endogenous free-running period that lasts approximately 24 hours.'''  The rhythm persists in constant conditions, (i.e., constant darkness) with a period of about 24 hours. The period of the rhythm in constant conditions is called the free-running period and is denoted by the Greek letter τ (tau).  The rationale for this criterion is to distinguish circadian rhythms from simple responses to daily external cues. A rhythm cannot be said to be [[endogenous]] unless it has been tested and persists in conditions without external periodic input.  In diurnal animals (active during daylight hours), in general τ is slightly greater than 24 hours, whereas, in nocturnal animals (active at night), in general τ is shorter than 24 hours.
# '''The rhythms are entrainable.''' The rhythm can be reset by exposure to external stimuli (such as light and heat), a process called [[Entrainment (chronobiology)|entrainment]]. The external stimulus used to entrain a rhythm is called the [[Zeitgeber]], or "time giver".  Travel across [[time zone]]s illustrates the ability of the human biological clock to adjust to the local time; a person will usually experience [[jet lag]] before entrainment of their circadian clock has brought it into sync with local time.
# '''The rhythms exhibit temperature compensation.''' In other words, they maintain circadian periodicity over a range of physiological temperatures. Many organisms live at a broad range of temperatures, and differences in thermal energy will affect the [[Chemical kinetics|kinetics]] of all molecular processes in their cell(s). In order to keep track of time, the organism's circadian clock must maintain roughly a 24-hour periodicity despite the changing kinetics, a property known as temperature compensation.  The [[Q10 (temperature coefficient)|Q10 Temperature Coefficient]] is a measure of this compensating effect. If the Q10 coefficient remains approximately 1 as temperature increases, the rhythm is considered to be temperature-compensated.

==Origin==
Circadian rhythms allow organisms to anticipate and prepare for precise and regular environmental changes. They thus enable organisms to better capitalize on environmental resources (e.g. light and food) compared to those that cannot predict such availability. It has therefore been suggested that circadian rhythms put organisms at a selective advantage in evolutionary terms. However, rhythmicity appears to be as important in regulating and coordinating ''internal'' metabolic processes, as in coordinating with the ''environment''.<ref>{{cite journal | vauthors = Sharma VK | title = Adaptive significance of circadian clocks | journal = Chronobiology International | volume = 20 | issue = 6 | pages = 901–19 | date = November 2003 | pmid = 14680135 | doi = 10.1081/CBI-120026099 }}</ref> This is suggested by the maintenance (heritability) of circadian rhythms in fruit flies after several hundred generations in constant laboratory conditions,<ref>{{primary source inline|date=November 2013}} {{cite journal | vauthors = Sheeba V, Sharma VK, Chandrashekaran MK, Joshi A | title = Persistence of eclosion rhythm in Drosophila melanogaster after 600 generations in an aperiodic environment | journal = Die Naturwissenschaften | volume = 86 | issue = 9 | pages = 448–9 | date = September 1999 | pmid = 10501695 | doi = 10.1007/s001140050651 | bibcode = 1999NW.....86..448S }}</ref> as well as in creatures in constant darkness in the wild, and by the experimental elimination of behavioral, but not physiological, circadian rhythms in [[quail]].<ref>{{primary source inline|date=November 2013}} {{cite journal | vauthors = Guyomarc'h C, Lumineau S, Richard JP | title = Circadian rhythm of activity in Japanese quail in constant darkness: variability of clarity and possibility of selection | journal = Chronobiology International | volume = 15 | issue = 3 | pages = 219–30 | date = May 1998 | pmid = 9653576 | doi = 10.3109/07420529808998685 }}</ref><ref>{{primary source inline|date=November 2013}} {{cite journal | vauthors = Zivkovic BD, Underwood H, Steele CT, Edmonds K | title = Formal properties of the circadian and photoperiodic systems of Japanese quail: phase response curve and effects of T-cycles | journal = Journal of Biological Rhythms | volume = 14 | issue = 5 | pages = 378–90 | date = October 1999 | pmid = 10511005 | doi = 10.1177/074873099129000786 }}</ref>

What drove circadian rhythms to evolve has been an enigmatic question. Previous hypotheses emphasized that photosensitive proteins and circadian rhythms may have originated together in the earliest cells, with the purpose of protecting replicating DNA from high levels of damaging [[ultraviolet]] radiation during the daytime. As a result, replication was relegated to the dark. However, evidence for this is lacking, since the simplest organisms with a circadian rhythm, the cyanobacteria, do the opposite of this - they divide more in the daytime.<ref>{{cite journal | vauthors = Mori T, Johnson CH | title = Independence of circadian timing from cell division in cyanobacteria | journal = Journal of Bacteriology | volume = 183 | issue = 8 | pages = 2439–44 | date = April 2001 | pmid = 11274102 | pmc = 95159 | doi = 10.1128/JB.183.8.2439-2444.2001 | url = http://jb.asm.org/content/183/8/2439 }}</ref> Recent studies instead highlight the importance of co-evolution of redox proteins with circadian oscillators in all three domains of life following the [[Great Oxidation Event]] approximately 2.3 billion years ago.<ref name="Edgar 459–464"/><ref name="Bass 348–356"/> The current view is that circadian changes in environmental oxygen levels and the production of [[reactive oxygen species]] (ROS) in the presence of daylight are likely to have driven a need to evolve circadian rhythms to preempt, and therefore counteract, damaging redox reactions on a daily basis.

The simplest known [[circadian clock]]s are [[bacterial circadian rhythms]], exemplified by the prokaryote [[cyanobacteria]]. Recent research has demonstrated that the circadian clock of ''Synechococcus elongatus'' can be reconstituted ''in vitro'' with just the three proteins ([[KaiA]], [[KaiB]], [[KaiC]])<ref>{{cite journal | vauthors = Hut RA, Beersma DG | title = Evolution of time-keeping mechanisms: early emergence and adaptation to photoperiod | journal = Philosophical Transactions of the Royal Society of London. Series B, Biological Sciences | volume = 366 | issue = 1574 | pages = 2141–54 | date = July 2011 | pmid = 21690131 | pmc = 3130368 | doi = 10.1098/rstb.2010.0409 }}</ref> of their central oscillator. This clock has been shown to sustain a 22-hour rhythm over several days upon the addition of [[Adenosine triphosphate|ATP]]. Previous explanations of the [[prokaryotic]] circadian timekeeper were dependent upon a DNA transcription/translation feedback mechanism.{{citation needed|date=November 2013}}

A defect in the human homologue of the ''[[Drosophila]]'' "[[period (gene)|period]]" gene was identified as a cause of the sleep disorder FASPS ([[Familial advanced sleep phase syndrome]]), underscoring the conserved nature of the molecular circadian clock through evolution. Many more genetic components of the biological clock are now known. Their interactions result in an interlocked feedback loop of gene products resulting in periodic fluctuations that the cells of the body interpret as a specific time of the day.<ref>{{cite journal | vauthors = Dubowy C, Sehgal A | title = Drosophila melanogaster | journal = Genetics | volume = 205 | issue = 4 | pages = 1373–1397 | date = April 2017 | pmid = 28360128 | pmc = 5378101 | doi = 10.1534/genetics.115.185157 }}</ref>

It is now known that the molecular circadian clock can function within a single cell; i.e., it is cell-autonomous.<ref>{{MEDRS|date=November 2013}} {{cite journal | vauthors = Nagoshi E, Saini C, Bauer C, Laroche T, Naef F, Schibler U | title = Circadian gene expression in individual fibroblasts: cell-autonomous and self-sustained oscillators pass time to daughter cells | journal = Cell | volume = 119 | issue = 5 | pages = 693–705 | date = November 2004 | pmid = 15550250 | doi = 10.1016/j.cell.2004.11.015 }}</ref> This was shown by [[Gene Block]] in isolated mollusk BRNs.{{clarify|date=April 2013}}<ref>{{primary source inline|date=November 2013}} {{cite journal | vauthors = Michel S, Geusz ME, Zaritsky JJ, Block GD | title = Circadian rhythm in membrane conductance expressed in isolated neurons | journal = Science | volume = 259 | issue = 5092 | pages = 239–41 | date = January 1993 | pmid = 8421785 | doi = 10.1126/science.8421785 | bibcode = 1993Sci...259..239M }}</ref> At the same time, different cells may communicate with each other resulting in a synchronised output of electrical signaling. These may interface with endocrine glands of the brain to result in periodic release of hormones. The receptors for these hormones may be located far across the body and synchronise the peripheral clocks of various organs. Thus, the information of the time of the day as relayed by the [[Human eye|eye]]s travels to the clock in the brain, and, through that, clocks in the rest of the body may be synchronised. This is how the timing of, for example, sleep/wake, body temperature, thirst, and appetite are coordinately controlled by the biological clock.<ref>{{cite journal | vauthors = Refinetti R | title = The circadian rhythm of body temperature | journal = Frontiers in Bioscience | volume = 15 | issue = 3 | pages = 564–94 | date = January 2010 | pmid = 20036834 | doi = 10.1016/0031-9384(92)90188-8 }}</ref><ref>{{cite journal | vauthors = Scheer FA, Morris CJ, Shea SA | title = The internal circadian clock increases hunger and appetite in the evening independent of food intake and other behaviors | journal = Obesity | volume = 21 | issue = 3 | pages = 421–3 | date = March 2013 | pmid = 23456944 | pmc = 3655529 | doi = 10.1002/oby.20351 }}</ref>

==Importance in animals==
Circadian rhythmicity is present in the sleeping and feeding patterns of animals, including human beings. There are also clear patterns of core body temperature, [[Neural oscillation|brain wave]] activity, [[hormone]] production, cell regeneration, and other biological activities. In addition, [[photoperiodism]], the physiological reaction of organisms to the length of day or night, is vital to both plants and animals, and the circadian system plays a role in the measurement and interpretation of day length. Timely prediction of seasonal periods of weather conditions, food availability, or predator activity is crucial for survival of many species. Although not the only parameter, the changing length of the photoperiod ('daylength') is the most predictive environmental cue for the seasonal timing of physiology and behavior, most notably for timing of migration, hibernation, and reproduction.<ref>{{MEDRS|date=November 2013}}  {{cite web |title= Clock Tutorial #16: Photoperiodism – Models and Experimental Approaches (original work from 2005-08-13) |url=http://scienceblogs.com/clock/2007/07/clock_tutorial_16_photoperiodi_1.php |access-date=2007-12-09 |last=Zivkovic |first=Bora "Coturnix" |date= 2007-07-25 |work=A Blog Around the Clock |publisher=ScienceBlogs}}</ref>

===Effect of circadian disruption===
Mutations or deletions of clock gene in mice have demonstrated the importance of body clocks to ensure the proper timing of cellular/metabolic events; clock-mutant mice are [[Polyphagia|hyperphagic]] and obese, and have altered glucose metabolism.<ref name="pmid15845877">{{primary source inline|date=December 2013}} {{cite journal | vauthors = Turek FW, Joshu C, Kohsaka A, Lin E, Ivanova G, McDearmon E, Laposky A, Losee-Olson S, Easton A, Jensen DR, Eckel RH, Takahashi JS, Bass J | title = Obesity and metabolic syndrome in circadian Clock mutant mice | journal = Science | volume = 308 | issue = 5724 | pages = 1043–5 | date = May 2005 | pmid = 15845877 | pmc = 3764501 | doi = 10.1126/science.1108750 | bibcode = 2005Sci...308.1043T | displayauthors = etal }}</ref> In mice, deletion of the [[Rev-ErbA alpha]] clock gene facilitates diet-induced obesity and changes the balance between glucose and lipid utilization predisposing to diabetes.<ref name="pmid22562834">{{cite journal | vauthors = Delezie J, Dumont S, Dardente H, Oudart H, Gréchez-Cassiau A, Klosen P, Teboul M, Delaunay F, Pévet P, Challet E | title = The nuclear receptor REV-ERBα is required for the daily balance of carbohydrate and lipid metabolism | journal = FASEB Journal | volume = 26 | issue = 8 | pages = 3321–35 | date = August 2012 | pmid = 22562834 | doi = 10.1096/fj.12-208751 | url = http://www.fasebj.org/content/26/8/3321.long | displayauthors = etal }}</ref> However, it is not clear whether there is a strong association between clock gene polymorphisms in humans and the susceptibility to develop the metabolic syndrome.<ref name="pmid22828941">{{primary source inline|date=December 2013}} {{cite journal | vauthors = Delezie J, Dumont S, Dardente H, Oudart H, Gréchez-Cassiau A, Klosen P, Teboul M, Delaunay F, Pévet P, Challet E | title = The nuclear receptor REV-ERBα is required for the daily balance of carbohydrate and lipid metabolism | journal = FASEB Journal | volume = 26 | issue = 8 | pages = 3321–35 | date = August 2012 | pmid = 22562834 | doi = 10.1096/fj.12-208751 | displayauthors = etal }}</ref><ref name="pmid18071340">{{primary source inline|date=December 2013}} {{cite journal | vauthors = Scott EM, Carter AM, Grant PJ | title = Association between polymorphisms in the Clock gene, obesity and the metabolic syndrome in man | journal = International Journal of Obesity | volume = 32 | issue = 4 | pages = 658–62 | date = April 2008 | pmid = 18071340 | doi = 10.1038/sj.ijo.0803778 }}</ref>

===Effect of light–dark cycle===
The rhythm is linked to the light–dark cycle. Animals, including humans, kept in total darkness for extended periods eventually function with a [[free-running sleep|free-running]] rhythm. Their sleep cycle is pushed back or forward each "day", depending on whether their "day", their [[endogenous]] period, is shorter or longer than 24 hours. The environmental cues that reset the rhythms each day are called zeitgebers (from the German, "time-givers").<ref name=health.am>{{MEDRS|date=November 2013}}  {{cite web |author1=Shneerson, J.M. |author2=Ohayon, M.M. |author3=Carskadon, M.A. |title=Circadian rhythms |publisher=Armenian Medical Network |work=Rapid eye movement (REM) sleep |url=http://www.sleep.health.am/sleep/more/circadian-rhythms/ |year=2007 |access-date=2007-09-19}}</ref> Totally blind subterranean mammals, e.g., [[blind mole rat]] ''Spalax'' sp., are able to maintain their endogenous clocks in the apparent absence of external stimuli. Although they lack image-forming eyes, their photoreceptors (which detect light) are still functional; they do surface periodically as well.{{page needed|date=November 2013}}<ref>"The Rhythms of Life: The Biological Clocks That Control the Daily Lives of Every Living Thing" Russell Foster & Leon Kreitzman, Publisher: Profile Books Ltd.</ref>

Free-running organisms that normally have one or two consolidated sleep episodes will still have them when in an environment shielded from external cues, but the rhythm is not entrained to the 24-hour light–dark cycle in nature. The sleep–wake rhythm may, in these circumstances, become out of phase with other circadian or [[ultradian]] rhythms such as metabolic, hormonal, CNS electrical, or neurotransmitter rhythms.<ref>{{MEDRS|date=November 2013}} {{cite journal | vauthors = Regestein QR, Pavlova M | title = Treatment of delayed sleep phase syndrome | journal = General Hospital Psychiatry | volume = 17 | issue = 5 | pages = 335–45 | date = September 1995 | pmid = 8522148 | doi = 10.1016/0163-8343(95)00062-V }}</ref>

Recent research has influenced the design of [[human spaceflight|spacecraft]] environments, as systems that mimic the light–dark cycle have been found to be highly beneficial to astronauts.<ref>{{MEDRS|date=November 2013}} {{cite web | url=http://www.space.com/18917-astronauts-insomnia-light-bulbs.html | author=Elizabeth Howell | title=Space Station to Get New Insomnia-Fighting Light Bulbs | date=14 December 2012 | access-date=2012-12-17}}</ref>

===Arctic animals===
Norwegian researchers at the [[University of Tromsø]] have shown that some [[Arctic#Biota|Arctic animals]] ([[Rock Ptarmigan|ptarmigan]], [[reindeer]]) show circadian rhythms only in the parts of the year that have daily sunrises and sunsets. In one study of reindeer, animals at [[70th parallel north|70 degrees North]] showed circadian rhythms in the autumn, winter and spring, but not in the summer.  Reindeer on [[Svalbard]] at [[78th parallel north|78 degrees North]] showed such rhythms only in autumn and spring. The researchers suspect that other Arctic animals as well may not show circadian rhythms in the constant light of summer and the constant dark of winter.<ref>{{primary source inline|date=November 2013}}  {{Cite news |first=Ingrid |last=Spilde |title=Reinsdyr uten døgnrytme |url=http://www.forskning.no/Artikler/2005/desember/1135264557.29 |publisher=forskning.no |date=December 2005 |access-date=2007-11-24 |language=Norwegian Bokmål|quote=...så det ikke ut til at reinen hadde noen døgnrytme om sommeren. Svalbardreinen hadde det heller ikke om vinteren.}}</ref>

A 2006 study in northern Alaska found that day-living [[ground squirrel]]s and nocturnal [[porcupine]]s strictly maintain their circadian rhythms through 82 days and nights of sunshine. The researchers speculate that these two rodents notice that the apparent distance between the sun and the horizon is shortest once a day, and, thus, a sufficient signal to entrain (adjust) by.<ref>{{cite journal |title=Mammalian activity – rest rhythms in Arctic continuous daylight |journal=Biological Rhythm Research |date=2006-12-01 |last=Folk |first=G. Edgar |last2=Thrift |first2=Diana L. |last3=Zimmerman |first3=M. Bridget |last4=Reimann |first4=Paul |volume=37 |issue=6 |pages=455–469 |doi=10.1080/09291010600738551 |url=http://www.tandfonline.com/doi/abs/10.1080/09291010600738551#.VB7Ql7kcSuo |access-date=2014-09-21 |quote=Would local animals maintained under natural continuous daylight demonstrate the Aschoff effect described in previously published laboratory experiments using continuous light, in which rats' circadian activity patterns changed systematically to a longer period, expressing a 26-hour day of activity and rest? }}</ref>

===Butterfly and moth===
The navigation of the fall migration of the [[monarch butterfly|Eastern North American monarch butterfly]] (''Danaus plexippus'') to their overwintering grounds in central Mexico uses a time-compensated sun compass that depends upon a circadian clock in their antennae.<ref>{{primary source inline|date=November 2013}} {{cite journal | vauthors = Merlin C, Gegear RJ, Reppert SM | title = Antennal circadian clocks coordinate sun compass orientation in migratory monarch butterflies | journal = Science | volume = 325 | issue = 5948 | pages = 1700–4 | date = September 2009 | pmid = 19779201 | pmc = 2754321 | doi = 10.1126/science.1176221 | bibcode = 2009Sci...325.1700M }}</ref><ref>{{primary source inline|date=November 2013}} {{cite journal | vauthors = Kyriacou CP | title = Physiology. Unraveling traveling | journal = Science | volume = 325 | issue = 5948 | pages = 1629–30 | date = September 2009 | pmid = 19779177 | doi = 10.1126/science.1178935 }}</ref> Also, circadian rhythm is also known to control mating behavior in certain moth species such as ''[[Spodoptera littoralis]]'', where females produce specific [[pheromone]] that attracts and resets the male circadian rhythm to induce mating at night.<ref>{{cite journal | vauthors = Silvegren G, Löfstedt C, Qi Rosén W | title = Circadian mating activity and effect of pheromone pre-exposure on pheromone response rhythms in the moth Spodoptera littoralis | journal = Journal of Insect Physiology | volume = 51 | issue = 3 | pages = 277–86 | date = March 2005 | pmid = 15749110 | doi = 10.1016/j.jinsphys.2004.11.013 | url = http://www.sciencedirect.com/science/article/pii/S0022191004002070 }}</ref>

==In plants==
<!-- Deleted image removed: [[File:TOC1 interactions.jpg|thumb|Illustration of the morning (yellow) and evening (gray) circadian clock loops in 
''Arabidopsis'', entrainable through light. Transcriptional regulation is shown through black lines and protein complexes are denoted by dashed black lines. Post-translational regulation is shown by dashed red lines. Light sensitive elements are denoted with lightning bolts and yellow circles.]] -->
[[File:Jungpflanze des Seidenbaums (Schlafbaum).png|thumb|Sleeping tree by day and night]]
Plant circadian rhythms tell the plant what season it is and when to flower for the best chance of attracting pollinators. Behaviors showing rhythms include leaf movement, growth, germination, stomatal/gas exchange, enzyme activity, photosynthetic activity, and fragrance emission, among others.<ref name=webb03>{{Cite journal |author=Webb AAR |date=June 2003 |title=The physiology of circadian rhythms in plants |journal=New Phytologist |volume=160 |issue=2 |pages=281–303 |jstor=1514280 |doi= 10.1046/j.1469-8137.2003.00895.x}}</ref> Circadian rhythms occur as a plant entrains to synchronize with the light cycle of its surrounding environment. These rhythms are endogenously generated and self-sustaining and are relatively constant over a range of ambient temperatures. Important features include two interacting transcription-translation feedback loops: proteins containing PAS domains, which facilitate protein-protein interactions; and several photoreceptors that fine-tune the clock to different light conditions. Anticipation of changes in the environment allows appropriate changes in a plant's physiological state, conferring an adaptive advantage.<ref name=mcclung06>{{cite journal | vauthors = McClung CR | title = Plant circadian rhythms | journal = The Plant Cell | volume = 18 | issue = 4 | pages = 792–803 | date = April 2006 | pmid = 16595397 | pmc = 1425852 | doi = 10.1105/tpc.106.040980 }}</ref> A better understanding of plant circadian rhythms has applications in agriculture, such as helping farmers stagger crop harvests to extend crop availability and securing against massive losses due to weather.

Light is the signal by which plants synchronize their internal clocks to their environment and is sensed by a wide variety of photoreceptors. Red and blue light are absorbed through several phytochromes and [[cryptochrome]]s. One phytochrome, phyA, is the main phytochrome in seedlings grown in the dark but rapidly degrades in light to produce Cry1. Phytochromes B–E are more stable with phyB, the main phytochrome in seedlings grown in the light. The cryptochrome (cry) gene is also a light-sensitive component of the circadian clock and is thought to be involved both as a photoreceptor and as part of the clock's endogenous pacemaker mechanism. Cryptochromes 1–2 (involved in blue–UVA) help to maintain the period length in the clock through a whole range of light conditions.<ref name=webb03/><ref name=mcclung06/>

The central oscillator generates a self-sustaining rhythm and is driven by two interacting feedback loops that are active at different times of day. The morning loop consists of CCA1 (Circadian and Clock-Associated 1) and LHY (Late Elongated Hypocotyl), which encode closely related MYB transcription factors that regulate circadian rhythms in ''Arabidopsis'', as well as PRR 7 and 9 (Pseudo-Response Regulators.)  The evening loop consists of GI (Gigantea) and ELF4, both involved in regulation of flowering time genes.<ref name=Mizoguchi>{{cite journal | vauthors = Mizoguchi T, Wright L, Fujiwara S, Cremer F, Lee K, Onouchi H, Mouradov A, Fowler S, Kamada H, Putterill J, Coupland G | title = Distinct roles of GIGANTEA in promoting flowering and regulating circadian rhythms in Arabidopsis | journal = The Plant Cell | volume = 17 | issue = 8 | pages = 2255–70 | date = August 2005 | pmid = 16006578 | pmc = 1182487 | doi = 10.1105/tpc.105.033464 | displayauthors = etal }}</ref><ref>{{cite journal | vauthors = Kolmos E, Davis SJ | title = ELF4 as a Central Gene in the Circadian Clock | journal = Plant Signaling & Behavior | volume = 2 | issue = 5 | pages = 370–2 | date = September 2007 | pmid = 19704602 | pmc = 2634215 | doi = 10.4161/psb.2.5.4463 }}</ref> When CCA1 and LHY are overexpressed (under constant light or dark conditions), plants become arrhythmic, and mRNA signals reduce, contributing to a negative feedback loop. Gene expression of CCA1 and LHY oscillates and peaks in the early morning, whereas [[TOC1 gene]] expression oscillates and peaks in the early evening. While it was previously hypothesised that these three genes model a negative feedback loop in which over-expressed CCA1 and LHY repress TOC1 and over-expressed TOC1 is a positive regulator of CCA1 and LHY,<ref name=mcclung06/> it was shown in 2012 by Andrew Millar and others that TOC1 in fact serves as a repressor not only of CCA1, LHY, and PRR7 and 9 in the morning loop but also of GI and ELF4 in the evening loop. This finding and further computational modeling of [[TOC1 gene]] functions and interactions suggest a reframing of the plant circadian clock as a triple negative-component [[repressilator]] model rather than the positive/negative-element feedback loop characterizing the clock in mammals.<ref>{{cite journal | vauthors = Pokhilko A, Fernández AP, Edwards KD, Southern MM, Halliday KJ, Millar AJ | title = The clock gene circuit in Arabidopsis includes a repressilator with additional feedback loops | journal = Molecular Systems Biology | volume = 8 | issue =  | pages = 574 | date = March 2012 | pmid = 22395476 | pmc = 3321525 | doi = 10.1038/msb.2012.6 }}</ref>

In 2018, researchers found that the expression of PRR5 and TOC1 hnRNA nascent transcripts follows the same oscillatory pattern as processed mRNA transcripts rhythmically in A.thaliana.LNKs binds to the 5'region of PRR5 and TOC1 and interacts with RNAP II and other transcription factors.Moreover,RVE8-LNKs interaction enables a permissive histone-methylation pattern(H3K4me3) to be modified and the histone-modification itself parallels the oscillation of clock gene expression.<ref>Yuan Ma, Sergio Gil, Klaus D. Grasser, Paloma Mas April 2018 "Targeted Recruitment of the Basal Transcriptional Machinery by LNK Clock Components Controls the Circadian Rhythms of Nascent RNAs in Arabidopsis"DOI: https://doi.org/10.1105/tpc.18.00052</ref>

==In ''Drosophila''==
{{Main|Drosophila circadian rhythm}}
[[File:Drosophila brains and the circadian system.jpg|thumb|Key centers of the mammalian and ''Drosophila'' brains (A) and the circadian system in ''Drosophila'' (B).]]
The molecular mechanism of circadian rhythm and light perception are best understood in ''Drosophila''. Clock genes are discovered from ''Drosophila'', and they act together with the clock neurones. There are two unique rhythms, one during the process of hatching (called [[eclosion]]) from the pupa, and the other during mating.<ref>{{cite journal | vauthors = Veleri S, Wülbeck C | title = Unique self-sustaining circadian oscillators within the brain of Drosophila melanogaster | journal = Chronobiology International | volume = 21 | issue = 3 | pages = 329–42 | date = May 2004 | pmid = 15332440 | doi = 10.1081/CBI-120038597 }}</ref> The clock neurones are located in distinct clusters in the central brain. The best-understood clock neurones are the large and small lateral ventral neurons (l-LNvs and s-LNvs) of the [[Optic lobe (arthropods)|optic lobe]]. These neurones produce pigment dispersing factor (PDF), a neuropeptide that acts as a circadian neuromodulator between different clock neurones.<ref name=yoshi>{{cite journal | vauthors = Yoshii T, Hermann-Luibl C, Helfrich-Förster C | title = Circadian light-input pathways in Drosophila | journal = Communicative & Integrative Biology | volume = 9 | issue = 1 | pages = e1102805 | date = 2015 | pmid = 27066180 | pmc = 4802797 | doi = 10.1080/19420889.2015.1102805 }}</ref>

[[File:Drosophila circadian rhythm.jpg|thumb|Molecular interactions of clock genes and proteins during ''Drosophila'' circadian rhythm.]]
''Drosophila'' circadian rhythm is through a transcription-translation feedback loop. The core clock mechanism consists of two interdependent feedback loops, namely the PER/TIM loop and the CLK/CYC loop.<ref>{{cite journal | vauthors = Boothroyd CE, Young MW | title = The in(put)s and out(put)s of the Drosophila circadian clock | journal = Annals of the New York Academy of Sciences | volume = 1129 | pages = 350–7 | date = 2008 | pmid = 18591494 | doi = 10.1196/annals.1417.006 }}</ref> The CLK/CYC loop occurs during the day and initiates the transcription of the ''per'' and ''tim'' genes. But their proteins levels remain low until dusk, because during daylight also activates the ''doubletime'' (''dbt'') gene. DBT protein causes phosphorylation and turnover of monomeric PER proteins.<ref>{{cite journal | vauthors = Grima B, Lamouroux A, Chélot E, Papin C, Limbourg-Bouchon B, Rouyer F | title = The F-box protein slimb controls the levels of clock proteins period and timeless | journal = Nature | volume = 420 | issue = 6912 | pages = 178–82 | date = November 2002 | pmid = 12432393 | doi = 10.1038/nature01122 }}</ref><ref>{{cite journal | vauthors = Ko HW, Jiang J, Edery I | title = Role for Slimb in the degradation of Drosophila Period protein phosphorylated by Doubletime | journal = Nature | volume = 420 | issue = 6916 | pages = 673–8 | date = December 2002 | pmid = 12442174 | doi = 10.1038/nature01272 }}</ref> TIM is also phosphorylated by shaggy until sunset. After sunset, DBT disappears, so that PER molecules stably bind to TIM. PER/TIM dimer enters the nucleus several at night, and binds to CLK/CYC dimers. Bound PER completely stops the transcriptional activity of CLK and CYC.<ref name=helfrich05>{{cite journal | vauthors = Helfrich-Förster C | title = Neurobiology of the fruit fly's circadian clock | journal = Genes, Brain, and Behavior | volume = 4 | issue = 2 | pages = 65–76 | date = March 2005 | pmid = 15720403 | doi = 10.1111/j.1601-183X.2004.00092.x }}</ref>

In the early morning, light activates the ''cry'' gene and its protein CRY causes the breakdown of TIM. Thus PER/TIM dimer dissociates, and the unbound PER becomes unstable. PER undergoes progressive phosphorylation and ultimately degradation. Absence of PER and TIM allows activation of ''clk'' and ''cyc'' genes. Thus, the clock is reset to start the next circadian cycle.<ref name="lalch">{{cite journal|last1=Lalchhandama|first1=K.|title=The path to the 2017 Nobel Prize in Physiology or Medicine|journal=Science Vision|date=2017|volume=3|issue=Suppl|pages=1–13|url=https://www.researchgate.net/publication/321533113_The_path_to_the_2017_Nobel_Prize_in_Physiology_or_Medicine}}</ref>

==In mammals==
[[File:Circadian rhythm labeled.jpg|thumb|400px|A variation of an [[Arnold Eskin#Eskinogram|eskinogram]] illustrating the influence of light and darkness on circadian rhythms and related [[physiology]] and behaviour through the [[suprachiasmatic nucleus]] in humans.]]
The primary [[circadian clock]] in [[mammal]]s is located in the [[suprachiasmatic nucleus]] (or nuclei) (SCN), a pair of distinct groups of [[cell (biology)|cells]] located in the [[hypothalamus]]. Destruction of the SCN results in the complete absence of a regular sleep–wake rhythm. The SCN receives information about illumination through the eyes. The [[retina]] of the eye contains "classical" [[photoreceptor cell|photoreceptors]] ("[[Rod cell|rods]]" and "[[Cone cell|cones]]"), which are used for conventional vision. But the retina also contains specialized [[Photosensitive ganglion cell|ganglion cell]]s that are directly photosensitive, and project directly to the SCN, where they help in the entrainment (synchronization) of this master circadian clock.<ref name=HHMI-BioInteractive>{{cite web|title=Biological Clock in Mammals|url=http://www.hhmi.org/biointeractive/human-suprachiasmatic-nucleus|website=BioInteractive|publisher=Howard Hughes Medical Institute|access-date=5 May 2015}}</ref>

These cells contain the photopigment [[melanopsin]] and their signals follow a pathway called the [[retinohypothalamic tract]], leading to the SCN. If cells from the SCN are removed and cultured, they maintain their own rhythm in the absence of external cues.<ref name=Welsh2010>{{cite journal | vauthors = Welsh DK, Takahashi JS, Kay SA | title = Suprachiasmatic nucleus: cell autonomy and network properties | journal = Annual Review of Physiology | volume = 72 | pages = 551–77 | date = March 2010 | pmid = 20148688 | pmc = 3758475 | doi = 10.1146/annurev-physiol-021909-135919 }}</ref>

The SCN takes the information on the lengths of the day and night from the retina, interprets it, and passes it on to the [[pineal gland]], a tiny structure shaped like a [[pine cone]] and located on the [[epithalamus]]. In response, the pineal secretes the hormone [[melatonin]]. Secretion of melatonin peaks at night and ebbs during the day and its presence provides information about night-length.{{citation needed|date=November 2013}}

Several studies have indicated that pineal melatonin feeds back on SCN rhythmicity to modulate circadian patterns of activity and other processes. However, the nature and system-level significance of this feedback are unknown.<ref>{{cite news|last1=Kalpesh|first1=J|title=Wellness With Artificial Light|url=http://www.walalight.com/white-paper-released-on-promoting-elder-wellness-with-artificial-light/|access-date=11 January 2016}}</ref>

The circadian rhythms of humans can be entrained to slightly shorter and longer periods than the Earth's 24 hours. Researchers at Harvard have shown that human subjects can at least be entrained to a 23.5-hour cycle and a 24.65-hour cycle (the latter being the natural solar day-night cycle on the planet [[Mars]]).<ref>{{MEDRS|date=November 2013}} {{cite journal | vauthors = Scheer FA, Wright KP, Kronauer RE, Czeisler CA | title = Plasticity of the intrinsic period of the human circadian timing system | journal = PloS One | volume = 2 | issue = 8 | pages = e721 | date = August 2007 | pmid = 17684566 | pmc = 1934931 | doi = 10.1371/journal.pone.0000721 | bibcode = 2007PLoSO...2..721S }}</ref>

=== Humans ===
Early research into circadian rhythms suggested that most people preferred a day closer to 25 hours when isolated from external stimuli like daylight and timekeeping. However, this research was faulty because it failed to shield the participants from artificial light. Although subjects were shielded from time cues (like clocks) and daylight, the researchers were not aware of the phase-delaying effects of indoor electric lights.<ref>{{MEDRS|date=November 2013}} {{cite journal | vauthors = Duffy JF, Wright KP | title = Entrainment of the human circadian system by light | journal = Journal of Biological Rhythms | volume = 20 | issue = 4 | pages = 326–38 | date = August 2005 | pmid = 16077152 | doi = 10.1177/0748730405277983 }}</ref>{{Dubious|reason=This is part review, part study, needs to be checked for proper use of secondary source|date=July 2014}} The subjects were allowed to turn on light when they were awake and to turn it off when they wanted to sleep. Electric light in the evening delayed their circadian phase.{{citation needed|date=November 2013}} A more stringent study conducted in 1999 by [[Harvard University]] estimated the natural human rhythm to be closer to 24 hours and 11 minutes: much closer to the [[Solar time|solar day]].<ref>{{cite journal|url=http://news.harvard.edu/gazette/1999/07.15/bioclock24.html|first=William|last=Cromie|title=Human Biological Clock Set Back an Hour|journal=Harvard Gazette|date=1999-07-15|access-date=2015-07-04}}</ref>

=== Biological markers and effects ===
The classic phase markers for measuring the timing of a mammal's circadian rhythm are:
* [[melatonin]] secretion by the [[pineal gland]],<ref name="Benloucif">{{cite journal | vauthors = Benloucif S, Guico MJ, Reid KJ, Wolfe LF, L'hermite-Balériaux M, Zee PC | title = Stability of melatonin and temperature as circadian phase markers and their relation to sleep times in humans | journal = Journal of Biological Rhythms | volume = 20 | issue = 2 | pages = 178–88 | date = April 2005 | pmid = 15834114 | doi = 10.1177/0748730404273983 }}</ref>
* [[Human body temperature|core body temperature]] minimum,<ref name="Benloucif" /> and
* plasma level of [[cortisol]].{{citation needed|date=November 2013}}
For temperature studies, subjects must remain awake but calm and semi-reclined in near darkness while their rectal temperatures are taken continuously. Though variation is great among normal [[chronotype]]s, the average human adult's temperature reaches its minimum at about 05:00 (5 a.m.), about two hours before habitual wake time. Baehr et al.<ref>{{cite journal | vauthors = Baehr EK, Revelle W, Eastman CI | title = Individual differences in the phase and amplitude of the human circadian temperature rhythm: with an emphasis on morningness-eveningness | journal = Journal of Sleep Research | volume = 9 | issue = 2 | pages = 117–27 | date = June 2000 | pmid = 10849238 | doi = 10.1046/j.1365-2869.2000.00196.x | url = http://www.blackwell-synergy.com/openurl?genre=article&sid=nlm:pubmed&issn=0962-1105&date=2000&volume=9&issue=2&spage=117 }}</ref> found that, in young adults, the daily body temperature minimum occurred at about 04:00 (4 a.m.) for morning types but at about 06:00 (6 a.m.) for evening types. This minimum occurred at approximately the middle of the eight-hour sleep period for morning types, but closer to waking in evening types.

Melatonin is absent from the system or undetectably low during daytime. Its onset in dim light, ''dim-light melatonin onset'' (DLMO), at roughly 21:00 (9 p.m.) can be measured in the blood or the saliva. Its major [[metabolite]] can also be measured in morning urine. Both DLMO and the midpoint (in time) of the presence of the hormone in the blood or saliva have been used as circadian markers. However, newer research indicates that the melatonin ''offset'' may be the more reliable marker. Benloucif et al.<ref name="Benloucif" /> found that melatonin phase markers were more stable and more highly correlated with the timing of sleep than the core temperature minimum. They found that both sleep offset and melatonin offset are more strongly correlated with phase markers than the onset of sleep. In addition, the declining phase of the melatonin levels is more reliable and stable than the termination of melatonin synthesis.

Other physiological changes that occur according to a circadian rhythm include [[heart rate]] and many cellular processes "including [[oxidative stress]], [[cell metabolism]], immune and inflammatory responses, [[epigenetics|epigenetic]] modification, [[Hypoxia (medical)|hypoxia]]/[[hyperoxia]] response pathways, [[Unfolded protein response|endoplasmic reticular stress]], [[autophagy]], and regulation of the [[stem cell]] environment."<ref name="workshop">{{cite web |url=http://www.nhlbi.nih.gov/research/reports/2014-circadian-clock-lung-health.htm |title=NHLBI Workshop:  "Circadian Clock at the Interface of Lung Health and Disease" 28-29 April 2014 Executive Summary  |author=<!--Staff writer(s); no by-line.--> |date=September 2014 |website= |publisher=National Heart, Lung, and Blood Institute |access-date=20 September 2014}}</ref> In a study of young men, it was found that the heart rate reaches its lowest average rate during sleep, and its highest average rate shortly after waking.<ref name="HeartRate">{{cite journal|last1=Cauter|first1=Eve Van|title=Quantitative Analysis of the 24-Hour Blood Pressure and Heart Rate Patterns in Young Men|journal=Hypertension|date=1991|volume=18|pages=199–210|doi=10.1161/01.hyp.18.2.199}}</ref>

In contradiction to previous studies, it has been found that there is no effect of body temperature on performance on psychological tests. This is likely due to evolutionary pressures for higher cognitive function compared to the other areas of function examined in previous studies.<ref>{{cite journal|last1=Quartel|first1=Lara|title=The effect of the circadian rhythm of body temperature on A-level exam performance|journal=Undergraduate Journal of Psychology|date=2014|volume=27|issue=1|url=https://journals.uncc.edu/ujop/article/view/283/300}}</ref>

===Outside the "master clock"===
More-or-less independent circadian rhythms are found in many organs and cells in the body outside the suprachiasmatic nuclei (SCN), the "master clock".  Indeed, neuroscientist Joseph Takahashi and colleagues stated in a 2013 article that "almost every cell in the body contains a circadian clock."<ref>{{cite journal | vauthors = Mohawk JA, Green CB, Takahashi JS | title = Central and peripheral circadian clocks in mammals | journal = Annual Review of Neuroscience | volume = 35 | pages = 445–62 | date = July 14, 2013 | pmid = 22483041 | pmc = 3710582 | doi = 10.1146/annurev-neuro-060909-153128 }}</ref>  For example, these clocks, called peripheral oscillators, have been found in the adrenal gland, [[oesophagus]], [[lungs]], [[liver]], [[pancreas]], [[spleen]], [[thymus]], and skin.<ref>Id.</ref><ref>{{cite journal | vauthors = Pendergast JS, Niswender KD, Yamazaki S | title = Tissue-specific function of Period3 in circadian rhythmicity | journal = PloS One | volume = 7 | issue = 1 | pages = e30254 | date = January 11, 2012 | pmid = 22253927 | pmc = 3256228 | doi = 10.1371/journal.pone.0030254 }}</ref>  There is also some evidence that the olfactory bulb<ref>See, e.g., Hanspeter Herzel et al., Coupling governs entrainment range of circadian clocks, Molecular Systems Biology, vol. 6, pp. 438 et seq., at https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3010105/</ref> and prostate<ref>See, e.g., Koeffler et al., A role for the clock gene, Per1 in prostate cancer, 60 Cancer Research 7619 et seq. (Oct. 2009), at http://cancerres.aacrjournals.org/content/69/19/7619.</ref> may experience oscillations, at least when cultured.

Though oscillators in the skin respond to light, a systemic influence has not been proven.<ref>{{cite journal | vauthors = Kawara S, Mydlarski R, Mamelak AJ, Freed I, Wang B, Watanabe H, Shivji G, Tavadia SK, Suzuki H, Bjarnason GA, Jordan RC, Sauder DN | title = Low-dose ultraviolet B rays alter the mRNA expression of the circadian clock genes in cultured human keratinocytes | journal = The Journal of Investigative Dermatology | volume = 119 | issue = 6 | pages = 1220–3 | date = December 2002 | pmid = 12485420 | doi = 10.1046/j.1523-1747.2002.19619.x | url = http://www.nature.com/jid/journal/v119/n6/full/5603326a.html }}</ref> In addition, many oscillators, such as liver cells, for example, have been shown to respond to inputs other than light, such as feeding.<ref>See, e.g., Schibler et al., Restricted feeding uncouples circadian oscillators in peripheral tissues from the central pacemaker in the suprachiasmatic nucleus, in 14 Genes & Development 2950–2961 (Dec. 1, 2000), at https://www.ncbi.nlm.nih.gov/pmc/articles/PMC317100/.</ref>

==Light and the biological clock==
{{further information|Light effects on circadian rhythm}}
Light resets the biological clock in accordance with the [[phase response curve]] (PRC). Depending on the timing, light can advance or delay the circadian rhythm. Both the PRC and the required [[illuminance]] vary from species to species and lower light levels are required to reset the clocks in [[Nocturnality|nocturnal]] rodents than in humans.<ref>{{cite journal | vauthors = Duffy JF, Czeisler CA | title = Effect of Light on Human Circadian Physiology | journal = Sleep Medicine Clinics | volume = 4 | issue = 2 | pages = 165–177 | date = June 2009 | pmid = 20161220 | pmc = 2717723 | doi = 10.1016/j.jsmc.2009.01.004 }}</ref>

==Enforced longer cycles==
Studies by [[Nathaniel Kleitman]] in 1938 and by [[Derk-Jan Dijk]] and [[Charles Czeisler]] in the 1990s put human subjects on enforced 28-hour sleep–wake cycles, in constant dim light and with other time cues suppressed, for over a month. Because normal people cannot entrain to a 28-hour day in dim light if at all,<ref>{{cite journal | vauthors = Czeisler CA, Duffy JF, Shanahan TL, Brown EN, Mitchell JF, Rimmer DW, Ronda JM, Silva EJ, Allan JS, Emens JS, Dijk DJ, Kronauer RE | title = Stability, precision, and near-24-hour period of the human circadian pacemaker | journal = Science | volume = 284 | issue = 5423 | pages = 2177–81 | date = June 1999 | pmid = 10381883 | doi = 10.1126/science.284.5423.2177 }}</ref> this is referred to as a forced desynchrony protocol. Sleep and wake episodes are uncoupled from the endogenous circadian period of about 24.18 hours and researchers are allowed to assess the effects of circadian phase on aspects of sleep and wakefulness including [[sleep latency]] and other functions - both physiological, behavioral, and cognitive.<ref>{{Cite book |last=Aldrich |first=Michael S. |title=Sleep medicine |url=https://books.google.com/books?id=1jScwMrsmAMC&pg=RA1-PA65&lpg=RA1-PA65&dq=experimenting+with+the+28+hour+day |year=1999 |isbn=0-19-512957-1 |publisher=Oxford University Press |location=New York}}</ref><ref>{{Cite journal|last=Wyatt|first=James K|title=Circadian temperature and melatonin rhythms, sleep, and neurobehavioral function in humans living on a 20-h day|url=http://ajpregu.physiology.org/content/277/4/R1152|journal=American Journal of Physiology|volume=277|issue=4|page=R1152-R1163}}</ref><ref>{{cite journal | vauthors = Wright KP, Hull JT, Czeisler CA | title = Relationship between alertness, performance, and body temperature in humans | journal = American Journal of Physiology. Regulatory, Integrative and Comparative Physiology | volume = 283 | issue = 6 | pages = R1370-7 | date = December 2002 | pmid = 12388468 | doi = 10.1152/ajpregu.00205.2002 }}</ref><ref>{{cite journal | vauthors = Zhou X, Ferguson SA, Matthews RW, Sargent C, Darwent D, Kennaway DJ, Roach GD | title = Sleep, wake and phase dependent changes in neurobehavioral function under forced desynchrony | journal = Sleep | volume = 34 | issue = 7 | pages = 931–41 | date = July 2011 | pmid = 21731143 | doi = 10.5665/sleep.1130 | url = http://www.journalsleep.org/ViewAbstract.aspx?pid=28193 | pmc = 3119835 }}</ref><ref>{{cite journal | vauthors = Kosmadopoulos A, Sargent C, Darwent D, Zhou X, Dawson D, Roach GD | title = The effects of a split sleep-wake schedule on neurobehavioural performance and predictions of performance under conditions of forced desynchrony | journal = Chronobiology International | volume = 31 | issue = 10 | pages = 1209–17 | date = December 2014 | pmid = 25222348 | doi = 10.3109/07420528.2014.957763 }}</ref>

==Human health==
[[File:Day Sleepers crop.jpg|thumb|right|A short nap during the day does not affect circadian rhythms.]]
Timing of medical treatment in coordination with the body clock, [[Chronotherapy (treatment scheduling)|chronotherapeutics]], may significantly increase efficacy and reduce drug toxicity or adverse reactions.<ref>{{cite journal | vauthors = Grote L, Mayer J, Penzel T, Cassel W, Krzyzanek E, Peter JH, von Wichert P | title = Nocturnal hypertension and cardiovascular risk: consequences for diagnosis and treatment | journal = Journal of Cardiovascular Pharmacology | volume = 24 Suppl 2 | issue =  | pages = S26-38 | year = 1994 | pmid = 7898092 }}</ref>

A number of studies have concluded that a short period of sleep during the day, a [[power-nap]], does not have any measurable effect on normal circadian rhythms but can decrease stress and improve productivity.<ref>{{cite journal | vauthors = Hershner SD, Chervin RD | title = Causes and consequences of sleepiness among college students | journal = Nature and Science of Sleep | volume = 6 | pages = 73–84 | date = 2014-06-23 | pmid = 25018659 | pmc = 4075951 | doi = 10.2147/NSS.S62907 }}</ref><ref>{{cite journal | vauthors = Milner CE, Cote KA | title = Benefits of napping in healthy adults: impact of nap length, time of day, age, and experience with napping | journal = Journal of Sleep Research | volume = 18 | issue = 2 | pages = 272–81 | date = June 2009 | pmid = 19645971 | doi = 10.1111/j.1365-2869.2008.00718.x | url = http://onlinelibrary.wiley.com/doi/10.1111/j.1365-2869.2008.00718.x/pdf }}</ref><ref>{{cite journal | vauthors = Lovato N, Lack L | title = The effects of napping on cognitive functioning | journal = Progress in Brain Research | volume = 185 | pages = 155–66 | date = 2010 | pmid = 21075238 | doi = 10.1016/B978-0-444-53702-7.00009-9 }}</ref>

Health problems can result from a disturbance to the circadian rhythm.<ref name="Zelinski2014">{{cite journal | vauthors = Zelinski EL, Deibel SH, McDonald RJ | title = The trouble with circadian clock dysfunction: multiple deleterious effects on the brain and body | journal = Neuroscience and Biobehavioral Reviews | volume = 40 | issue = 40 | pages = 80–101 | date = March 2014 | pmid = 24468109 | doi = 10.1016/j.neubiorev.2014.01.007 }}</ref> Circadian rhythms also play a part in the [[reticular activating system]], which is crucial for maintaining a state of consciousness. A reversal in the sleep–wake cycle may be a sign or complication of [[uremia]],<ref>{{cite web |url=http://www.emedicine.com/emerg/topic500.htm |title=Renal Failure, Acute |access-date=2008-08-03 |vauthors=Sinert T, Peacock PR |date=10 May 2006 |publisher=eMedicine from WebMD}}</ref> [[azotemia]] or [[acute renal failure]].<ref>{{cite journal | vauthors = Maung SC, El Sara A, Chapman C, Cohen D, Cukor D | title = Sleep disorders and chronic kidney disease | journal = World Journal of Nephrology | volume = 5 | issue = 3 | pages = 224–32 | date = May 2016 | pmid = 27152260 | pmc = 4848147 | doi = 10.5527/wjn.v5.i3.224 }}</ref><ref>{{cite journal | vauthors = Nakano S, Uchida K, Kigoshi T, Azukizawa S, Iwasaki R, Kaneko M, Morimoto S | title = Circadian rhythm of blood pressure in normotensive NIDDM subjects. Its relationship to microvascular complications | journal = Diabetes Care | volume = 14 | issue = 8 | pages = 707–11 | date = August 1991 | pmid = 1954805 | doi = 10.2337/diacare.14.8.707 }}</ref>

Studies have also shown that light has a [[Light effects on circadian rhythm|direct effect]] on human health because of the way it influences the circadian rhythms.<ref>{{cite journal | vauthors = Figueiro MG, Rea MS, Bullough JD | title = Does architectural lighting contribute to breast cancer? | journal = Journal of Carcinogenesis | volume = 5 | issue =  | pages = 20 | date = August 2006 | pmid = 16901343 | pmc = 1557490 | doi = 10.1186/1477-3163-5-20 }}</ref>

===Indoor lighting===

Lighting requirements for circadian regulation are not simply the same as those for vision; planning of indoor lighting in offices and institutions is beginning to take this into account.<ref>{{cite journal|last1=Rea|first1=Mark S.|last2=Figueiro|first2=Mariana|last3=Bullough|first3=John|title=Circadian photobiology: an emerging framework for lighting practice and research|journal=Lighting Research Technology|date=May 2002|volume=34|issue=3|pages=177–187|doi=10.1191/1365782802lt057oa}}</ref> Animal studies on the effects of light in laboratory conditions have until recently considered light intensity ([[irradiance]]) but not color, which can be shown to "act as an essential regulator of biological timing in more natural settings".<ref>{{cite journal | vauthors = Walmsley L, Hanna L, Mouland J, Martial F, West A, Smedley AR, Bechtold DA, Webb AR, Lucas RJ, Brown TM | title = Colour as a signal for entraining the mammalian circadian clock | journal = PLoS Biology | volume = 13 | issue = 4 | pages = e1002127 | date = April 2015 | pmid = 25884537 | doi = 10.1371/journal.pbio.1002127 | url = http://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.1002127 }}</ref>

===Obesity and diabetes===
[[Obesity]] and [[diabetes]] are associated with lifestyle and genetic factors. Among those factors, disruption of the circadian clockwork and/or misalignment of the circadian timing system with the external environment (e.g., light-dark cycle) might play a role in the development of metabolic disorders.<ref name="Zelinski2014" />

[[Shift-work]] or chronic [[jet-lag]] have profound consequences on circadian and metabolic events in the body. Animals that are forced to eat during their resting period show increased body mass and altered expression of clock and metabolic genes.<ref>{{cite journal | vauthors = Johnston JD | title = Physiological responses to food intake throughout the day | journal = Nutrition Research Reviews | volume = 27 | issue = 1 | pages = 107–18 | date = June 2014 | pmid = 24666537 | pmc = 4078443 | doi = 10.1017/S0954422414000055 }}</ref>{{mcn|date=November 2013}} In humans, shift-work that favors irregular eating times is associated with altered insulin sensitivity and higher body mass. Shift-work also leads to increased metabolic risks for cardio-metabolic syndrome, hypertension, and inflammation.<ref name="pmid22211891">{{cite journal | vauthors = Delezie J, Challet E | title = Interactions between metabolism and circadian clocks: reciprocal disturbances | journal = Annals of the New York Academy of Sciences | volume = 1243 | issue =  | pages = 30–46 | date = December 2011 | pmid = 22211891 | doi = 10.1111/j.1749-6632.2011.06246.x | bibcode = 2011NYASA1243...30D }} <!-- this is only a partial review --></ref>

===Airline pilots and cabin crew===
Due to the work nature of airline pilots, who often cross several timezones and regions of sunlight and darkness in one day, and spend many hours awake both day and night, they are often unable to maintain sleep patterns that correspond to the natural human circadian rhythm; this situation can easily lead to [[fatigue (physical)|fatigue]]. The [[NTSB]] cites this as contributing to many accidents{{MEDRS|date=November 2013}} <ref>[http://www.aviationweek.com/aw/jsp_includes/articlePrint.jsp?storyID=news/FATIGex.xml&headLine=null ]{{dead link|date=December 2016}}</ref> and has conducted several research studies in order to find methods of combating fatigue in pilots.<ref>Circadian Rhythm Disruption and Flying. FAA at https://www.faa.gov/pilots/safety/pilotsafetybrochures/media/Circadian_Rhythm.pdf</ref>

===Disruption===
{{Further information|Circadian rhythm sleep disorder}}
Disruption to rhythms usually has a negative effect. Many travelers have experienced the condition known as [[jet lag]], with its associated symptoms of [[fatigue (physical)|fatigue]], disorientation, and [[insomnia]].<ref>{{Cite news|url=https://www.sleepassociation.org/circadian-rhythm-disorders-impact-sleep/|title=Circadian Rhythm Disorders and How They Impact Sleep|work=American Sleep Association|access-date=2018-01-29|language=en-US}}</ref>

A number of other disorders, for example [[bipolar disorder]] and some [[sleep disorder]]s such as [[delayed sleep phase disorder]] (DSPD), are associated with irregular or pathological functioning of circadian rhythms.<ref>{{cite journal | vauthors = Zhu L, Zee PC | title = Circadian rhythm sleep disorders | journal = Neurologic Clinics | volume = 30 | issue = 4 | pages = 1167–91 | date = November 2012 | pmid = 23099133 | pmc = 3523094 | doi = 10.1016/j.ncl.2012.08.011 }}</ref>{{mcn|date=November 2013}}

Disruption to rhythms in the longer term is believed to have significant adverse health consequences on peripheral organs outside the brain, in particular in the development or exacerbation of cardiovascular disease.<ref name="Zelinski2014" /><ref>Oritz-Tuldela E, Martinez-Nicolas A, Diaz-Mardomingo C, Garcia-Herranz S, Pereda-Perez I, Valencia A, Peraita H, Venero C, Madrid J, Rol M. 2014. The Characterization of Biological Rhythms in Mild Cognitive Impairment. BioMed Research International.</ref> Blue LED lighting suppresses melatonin production five times more than the orange-yellow [[Sodium-vapor lamp|high-pressure sodium (HPS) light]]; a [[metal halide lamp]], which is white light, suppresses melatonin at a rate more than three times greater than HPS.<ref>{{cite web|url=https://www.academia.edu/5960717/The_Dangers_of_LED-Blue_light-The_Suppression_of_Melatonin-Resulting_in-Insomnia-And_Cancers |title=The Dangers of LED-Blue light-The Suppression of Melatonin-Resulting in-Insomnia-And Cancers &#124; Robert Hardt |website=Academia.edu |date=1970-01-01 |access-date=2016-12-24}}</ref> Depression symptoms from long term nighttime light exposure can be undone by returning to a normal cycle.<ref>{{cite journal | vauthors = Bedrosian TA, Nelson RJ | title = Timing of light exposure affects mood and brain circuits | journal = Translational Psychiatry | volume = 7 | issue = 1 | pages = e1017 | date = January 2017 | pmid = 28140399 | pmc = 5299389 | doi = 10.1038/tp.2016.262 }}</ref>{{mcn|date=November 2013}}

===Effect of drugs===
Studies conducted on both animals and humans show major bidirectional relationships between the circadian system and abusive drugs.  It is indicated that these abusive drugs affect the central circadian pacemaker.  Individuals suffering from substance abuse display disrupted rhythms. These disrupted rhythms can increase the risk for substance abuse and relapse. It is possible that genetic and/or environmental disturbances to the normal sleep and wake cycle can increase the susceptibility to addiction.<ref name=Logan>{{cite journal | vauthors = Logan RW, Williams WP, McClung CA | title = Circadian rhythms and addiction: mechanistic insights and future directions | journal = Behavioral Neuroscience | volume = 128 | issue = 3 | pages = 387–412 | date = June 2014 | pmid = 24731209 | pmc = 4041815 | doi = 10.1037/a0036268 }}</ref>

It is difficult to determine if a disturbance in the circadian rhythm is at fault for an increase in prevalence for substance abuse or if other environmental factors such as stress are to blame.
Changes to the circadian rhythm and sleep occur once an individual begins abusing drugs and alcohol. Once an individual chooses to stop using drugs and alcohol, the circadian rhythm continues to be disrupted.<ref name=Logan/>

The stabilization of sleep and the circadian rhythm might possibly help to reduce the vulnerability to addiction and reduce the chances of relapse.<ref name=Logan/>

Circadian rhythms and clock genes expressed in brain regions outside the [[suprachiasmatic nucleus]] may significantly influence the effects produced by drugs such as [[cocaine]].{{citation needed|date=November 2013}} Moreover, genetic manipulations of clock genes profoundly affect cocaine's actions.<ref>{{cite journal | vauthors = Prosser RA, Glass JD | title = Assessing ethanol's actions in the suprachiasmatic circadian clock using in vivo and in vitro approaches | journal = Alcohol | volume = 49 | issue = 4 | pages = 321–339 | date = June 2015 | pmid = 25457753 | pmc = 4402095 | doi = 10.1016/j.alcohol.2014.07.016 }}</ref>

==Society and culture==
In 2017, [[Jeffrey C. Hall]], [[Michael W. Young]], and [[Michael Rosbash]] were awarded [[Nobel Prize in Physiology or Medicine]] "for their discoveries of molecular mechanisms controlling the circadian rhythm".<ref>{{cite news |last=Cha |first=Arlene Eujung |date=October 2, 2017 |title=Nobel in physiology, medicine awarded to three Americans for discovery of ‘clock genes’ |url=https://www.washingtonpost.com/news/to-your-health/wp/2017/10/02/nobel-prize-in-medicine-or-physiology-awarded-to-tktk/?hpid=hp_hp-more-top-stories_nobel-550am%3Ahomepage%2Fstory |work=[[Washington Post]] |access-date=October 2, 2017 }}</ref><ref name="Nobel Press Release">{{cite web|url=https://www.nobelprize.org/nobel_prizes/medicine/laureates/2017/press.html |title=The 2017 Nobel Prize in Physiology or Medicine – Press Release|publisher=The Nobel Foundation |date=October 2, 2017 |access-date=October 2, 2017}}</ref>

== See also ==
{{colbegin}}
* [[Actigraphy]] (also known as actimetry)
* [[ARNTL]]
* [[ARNTL2]]
* [[Bacterial circadian rhythms]]
* [[Circadian rhythm sleep disorders]], such as
** [[Advanced sleep phase disorder]]
** [[Delayed sleep phase disorder]]
** [[Non-24-hour sleep-wake disorder]]
* [[Circasemidian rhythm]]
* [[Circaseptan]], 7-day biological cycle
* [[Cryptochrome]]
* [[CRY1]] and [[CRY2]]: the cryptochrome family genes
* [[Diurnal cycle]]
* [[Light effects on circadian rhythm]]
* [[Light in school buildings]]
* [[PER1]], [[PER2]], and [[PER3]]: the period family genes
* [[Photosensitive ganglion cell]]: part of the eye which is involved in regulating circadian rhythm.
* [[Polyphasic sleep]]
* [[Rev-ErbA alpha]]
* [[Segmented sleep]]
* [[Sleep architecture]] (Sleep in Humans)
* [[Sleep in non-human animals]]
* [[Stefania Follini]]
{{colend}}

== References ==
{{Reflist|32em}}

== Further reading ==
{{Refbegin|32em}}
* Aschoff, J. (ed.) (1965) ''Circadian Clocks''. North Holland Press, Amsterdam
* {{cite journal | vauthors = Avivi A, Albrecht U, Oster H, Joel A, Beiles A, Nevo E | title = Biological clock in total darkness: the Clock/MOP3 circadian system of the blind subterranean mole rat | journal = Proceedings of the National Academy of Sciences of the United States of America | volume = 98 | issue = 24 | pages = 13751–6 | date = November 2001 | pmid = 11707566 | pmc = 61113 | doi = 10.1073/pnas.181484498 | bibcode = 2001PNAS...9813751A }}
* {{cite journal | vauthors = Avivi A, Oster H, Joel A, Beiles A, Albrecht U, Nevo E | title = Circadian genes in a blind subterranean mammal II: conservation and uniqueness of the three Period homologs in the blind subterranean mole rat, Spalax ehrenbergi superspecies | journal = Proceedings of the National Academy of Sciences of the United States of America | volume = 99 | issue = 18 | pages = 11718–23 | date = September 2002 | pmid = 12193657 | pmc = 129335 | doi = 10.1073/pnas.182423299 | bibcode = 2002PNAS...9911718A }}
* {{cite journal | vauthors = Li D, Ma S, Guo D, Cheng T, Li H, Tian Y, Li J, Guan F, Yang B, Wang J | title = Environmental Circadian Disruption Worsens Neurologic Impairment and Inhibits Hippocampal Neurogenesis in Adult Rats After Traumatic Brain Injury | journal = Cellular and Molecular Neurobiology | volume = 36 | issue = 7 | pages = 1045–55 | date = October 2016 | pmid = 26886755 | pmc = 4967018 | doi = 10.1007/s10571-015-0295-2 }}
* {{cite journal | vauthors = Ditty JL, Williams SB, Golden SS | title = A cyanobacterial circadian timing mechanism | journal = Annual Review of Genetics | volume = 37 | pages = 513–43 | year = 2003 | pmid = 14616072 | doi = 10.1146/annurev.genet.37.110801.142716 }}
* Dunlap, J.C.; Loros, J.; DeCoursey, P.J. (2003) ''Chronobiology: Biological Timekeeping''. Sinauer, Sunderland
* {{cite journal | vauthors = Dvornyk V, Vinogradova O, Nevo E | title = Origin and evolution of circadian clock genes in prokaryotes | journal = Proceedings of the National Academy of Sciences of the United States of America | volume = 100 | issue = 5 | pages = 2495–500 | date = March 2003 | pmid = 12604787 | pmc = 151369 | doi = 10.1073/pnas.0130099100 | bibcode = 2003PNAS..100.2495D }}
* Koukkari, W.L.; Sothern, R.B. (2006) ''Introducing Biological Rhythms''. Springer, New York
* {{cite journal | vauthors = Martino T, Arab S, Straume M, Belsham DD, Tata N, Cai F, Liu P, Trivieri M, Ralph M, Sole MJ | title = Day/night rhythms in gene expression of the normal murine heart | journal = Journal of Molecular Medicine | volume = 82 | issue = 4 | pages = 256–64 | date = April 2004 | pmid = 14985853 | doi = 10.1007/s00109-003-0520-1 }}
* Refinetti, R. (2006) ''Circadian Physiology, 2nd ed''. CRC Press, Boca Raton
* {{cite journal | vauthors = Takahashi JS, Zatz M | title = Regulation of circadian rhythmicity | journal = Science | volume = 217 | issue = 4565 | pages = 1104–11 | date = September 1982 | pmid = 6287576 | doi = 10.1126/science.6287576 | bibcode = 1982Sci...217.1104T }}
* {{cite journal | vauthors = Tomita J, Nakajima M, Kondo T, Iwasaki H | title = No transcription-translation feedback in circadian rhythm of KaiC phosphorylation | journal = Science | volume = 307 | issue = 5707 | pages = 251–4 | date = January 2005 | pmid = 15550625 | doi = 10.1126/science.1102540 | bibcode = 2005Sci...307..251T }}
* {{Cite book |last=Moore-Ede |first=Martin C. |last2=Sulzman |first2=Frank M. |last3=Fuller |first3=Charles A. |year=1982 |title=The Clocks that Time Us: Physiology of the Circadian Timing System |publisher= Harvard University Press |location=Cambridge, Massachusetts |isbn=0-674-13581-4}}
{{Refend}}

== External links ==
{{Commons category}}
* {{dmoz|Health/Conditions_and_Diseases/Sleep_Disorders/Biological_Rhythms}}

{{Light Ethology}}

{{DEFAULTSORT:Circadian Rhythm}}
[[Category:Sleep]]
[[Category:Circadian rhythm| ]]
[[Category:Biology of bipolar disorder]]
[[Category:Plant cognition]]
